set(_CATKIN_CURRENT_PACKAGE "ml_detector")
set(ml_detector_VERSION "0.0.0")
set(ml_detector_MAINTAINER "pryre <pryre@todo.todo>")
set(ml_detector_PACKAGE_FORMAT "1")
set(ml_detector_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "std_msgs" "sensor_msgs" "ml_msgs" "geometry_msgs" "tf2" "dynamic_reconfigure")
set(ml_detector_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "std_msgs" "sensor_msgs" "ml_msgs" "geometry_msgs" "tf2" "dynamic_reconfigure")
set(ml_detector_BUILDTOOL_DEPENDS "catkin")
set(ml_detector_BUILDTOOL_EXPORT_DEPENDS )
set(ml_detector_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "std_msgs" "sensor_msgs" "ml_msgs" "geometry_msgs" "tf2" "dynamic_reconfigure")
set(ml_detector_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "std_msgs" "sensor_msgs" "ml_msgs" "geometry_msgs" "tf2" "dynamic_reconfigure")
set(ml_detector_TEST_DEPENDS )
set(ml_detector_DOC_DEPENDS )
set(ml_detector_URL_WEBSITE "")
set(ml_detector_URL_BUGTRACKER "")
set(ml_detector_URL_REPOSITORY "")
set(ml_detector_DEPRECATED "")